---
- name: Add MongoDB3.4 repo
  yum_repository:
    name: mongo34
    description: mongo34 repo
    file: mongodb34
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc

- name: Install packages
  yum:
      state: present
      name:
          - mongodb-org
          - mongodb-org-server

- name: Disable MongoDB journal
  lineinfile:
      backrefs: yes
      dest: /etc/mongod.conf
      regexp: "^#nojournal = true"
      line: "nojournal = true"
  notify: restart mongod

- name: Start and enable services
  service:
    name: mongod
    state: started
    enabled: yes
